version: '3.7'

services:
  rasa:
    image: rasa/rasa:1.9.0-full
    networks:
      chatbot: ~
    volumes:
    - "./rasa-app-data/:/app/"
    command:
    - run

  action-server:
    image: rasa/rasa-sdk:1.9.0
    networks:
      chatbot: ~
    volumes:
    - "./rasa-app-data:/app/actions"

  duckling:
    image: rasa/duckling:0.1.6.2
    networks:
      chatbot: ~

  mm-db:
    image: mattermost/mattermost-prod-db:latest
    networks:
      chatbot: ~
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=Password1
    - POSTGRES_DB=mattermost

  mm-app:
    image: mattermost/mattermost-prod-app:latest
    networks:
      chatbot: ~
    environment:
    - DB_HOST=mm-db
    - MM_USERNAME=postgres
    - MM_PASSWORD=Password1
    - MM_DBNAME=mattermost
    - edition=team

  mm-web:
    image: mattermost/mattermost-prod-web:latest
    ports:
    - "8055:80"
    networks:
      chatbot: ~
    environment:
    - APP_HOST=mm-app
    - APP_PORT=80

networks: 
  chatbot: ~
